CREATE TABLE restaurants (
    Restaurant_ID SERIAL PRIMARY KEY,      
    Restaurant_name VARCHAR(255),          
    Cuisines TEXT,                         
    Address TEXT,                          
    Locality_verbose TEXT,                 
    Locality VARCHAR(150),                
    City VARCHAR(150),                   
    Country_ID INT,                       
    Average_cost_for_two NUMERIC(10, 2),  
    Price_range INT,                      
    Aggregate_rating NUMERIC(3, 2),        
    Rating_text VARCHAR(50),              
    Votes INT,                            
    Delivering_now BOOLEAN,               
    Online_delivery BOOLEAN,              
    Table_booking BOOLEAN,                
    order_menu BOOLEAN,                   
    Menu_url TEXT,                         
    Events_url TEXT,                      
    Longitude NUMERIC(9, 6),              
    Latitude NUMERIC(9, 6),               
    Currency VARCHAR(10)                  
);
